// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPINET8.Database;

#nullable disable

namespace WebAPINET8.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240117121028_pr0")]
    partial class pr0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebAPINET8.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            CorreoElectronico = "usuario1@example.com",
                            FechaRegistro = new DateTime(2024, 1, 17, 13, 10, 26, 586, DateTimeKind.Local).AddTicks(6174),
                            Nombre = "Usuario1"
                        },
                        new
                        {
                            UsuarioId = 2,
                            CorreoElectronico = "usuario2@example.com",
                            FechaRegistro = new DateTime(2024, 1, 17, 13, 10, 26, 586, DateTimeKind.Local).AddTicks(6235),
                            Nombre = "Usuario2"
                        },
                        new
                        {
                            UsuarioId = 3,
                            CorreoElectronico = "usuario3@example.com",
                            FechaRegistro = new DateTime(2024, 1, 17, 13, 10, 26, 586, DateTimeKind.Local).AddTicks(6237),
                            Nombre = "Usuario3"
                        },
                        new
                        {
                            UsuarioId = 4,
                            CorreoElectronico = "usuario4@example.com",
                            FechaRegistro = new DateTime(2024, 1, 17, 13, 10, 26, 586, DateTimeKind.Local).AddTicks(6239),
                            Nombre = "Usuario4"
                        },
                        new
                        {
                            UsuarioId = 5,
                            CorreoElectronico = "usuario5@example.com",
                            FechaRegistro = new DateTime(2024, 1, 17, 13, 10, 26, 586, DateTimeKind.Local).AddTicks(6240),
                            Nombre = "Usuario5"
                        },
                        new
                        {
                            UsuarioId = 6,
                            CorreoElectronico = "usuario6@example.com",
                            FechaRegistro = new DateTime(2024, 1, 17, 13, 10, 26, 586, DateTimeKind.Local).AddTicks(6242),
                            Nombre = "Usuario6"
                        },
                        new
                        {
                            UsuarioId = 7,
                            CorreoElectronico = "usuario7@example.com",
                            FechaRegistro = new DateTime(2024, 1, 17, 13, 10, 26, 586, DateTimeKind.Local).AddTicks(6243),
                            Nombre = "Usuario7"
                        },
                        new
                        {
                            UsuarioId = 8,
                            CorreoElectronico = "usuario8@example.com",
                            FechaRegistro = new DateTime(2024, 1, 17, 13, 10, 26, 586, DateTimeKind.Local).AddTicks(6245),
                            Nombre = "Usuario8"
                        },
                        new
                        {
                            UsuarioId = 9,
                            CorreoElectronico = "usuario9@example.com",
                            FechaRegistro = new DateTime(2024, 1, 17, 13, 10, 26, 586, DateTimeKind.Local).AddTicks(6247),
                            Nombre = "Usuario9"
                        },
                        new
                        {
                            UsuarioId = 10,
                            CorreoElectronico = "usuario10@example.com",
                            FechaRegistro = new DateTime(2024, 1, 17, 13, 10, 26, 586, DateTimeKind.Local).AddTicks(6248),
                            Nombre = "Usuario10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
